version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    open-pull-request-limit: 50
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
